security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
      client-id: user-service
      client-secret: 123456
    resource:
      user-info-uri: http://localhost:9999/api/v1/users/principal
      prefer-token-info: false
